### ISSUE TITLE
Discriminator should have a encoder-decoder architecture.

### ISSUE THREAD

**Issue by sooryamsharma** [rohitrango/Adversarial-Pose-Estimation#1]
Your discriminator model is just fully connected layers, whereas in the original implementation they (authors) have used encoder-decoder architecture for the two discriminators.

**Comment by abhishekdiphu** [comment]
The discriminator in the paper has a FCN architecture , with skip connection ,but I think in your implementation , you are using residual blocks .
More over I think  you did not use and adversarial loss for generator optimisation

I have  used a different discriminator with downsampling with normal convolution and then upsampling with transpose conv.
I have also used some skip connection like UNET architecture  with original final objective as mentioned in the paper and it worked for me.

**Comment by rohitrango** [comment]
@sooryamsharma @abhishekdiphu in the interest of time (it was a course project), I kept it barebones and didn't add a lot of things. This repo is meant to be a skeleton code for more advanced tweaks and I'm open to pull requests with more features.
