### ISSUE TITLE
Dataset link is not work!!

### ISSUE THREAD

**Issue by helloyuning** [rohitrango/Adversarial-Pose-Estimation#7]
As title, can you update the dataset link?
I really insterested in this work!!

Thanks,
yuning

**Comment by rohitrango** [comment]
you can use this link https://dbcollection.readthedocs.io/en/latest/datasets/leeds_sports_pose_extended.html

Edit: looks like the original dataset link is down.

**Comment by helloyuning** [comment]
> you can use this link https://dbcollection.readthedocs.io/en/latest/datasets/leeds_sports_pose_extended.html
> 
> Edit: looks like the original dataset link is down.

Thanks for your reply.
Due to others projects i can not start this work right now, do you have source data set? I checked the link but it seems can not down, if available i want to see real dataset(like what the data is, and how is it built) not only code.
And in descriminator part, what is the gound trulth, is it same as generator?

Sorry for many questions.

Thanks,
yuning

**Comment by rohitrango** [comment]
sorry, I do not have the ground truths.

yes, for discriminator real samples correspond to the images and corresponding keypoints from ground truth
